# =====================================
# debug.yml – korte SSH-connectiviteitstest
# =====================================
name: Debug SSH Connectivity
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      HOST: ${{ secrets.GAMESERVER_HOST }}
      USER: ${{ secrets.GAMESERVER_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Add host key
        run: ssh-keyscan -t ed25519 -H "$HOST" >> ~/.ssh/known_hosts

      - name: Controleer verbinding
        run: |
          ssh -o BatchMode=yes "$USER@$HOST" \
            'echo "Verbonden met $(hostname -f) als $(whoami)" && uptime && uname -r'

      - name: Installeer tmux en Java indien nodig
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          if ! command -v tmux >/dev/null; then
            echo "tmux ontbreekt; installeren…"
            sudo -n true 2>/dev/null && sudo apt-get update -qq && sudo apt-get install -y tmux || echo "Geen sudo-rechten; tmux niet geïnstalleerd"
          fi
          if ! java -version 2>&1 | grep -q "\(24\|17\)"; then
            echo "Java 24/17 ontbreekt; installeren…"
            sudo -n true 2>/dev/null && sudo apt-get update -qq && sudo apt-get install -y openjdk-24-jdk || sudo apt-get install -y openjdk-17-jdk || echo "Geen sudo-rechten; Java niet geïnstalleerd"
          fi
          EOS