name: Debug SSH Connectivity
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Show loaded SSH keys
        run: ssh-add -l

      - name: List ~/.ssh directory
        run: ls -la ~/.ssh || echo "~/.ssh directory does not exist"

      - name: Test basic connectivity
        run: |
          echo "Testing connectivity to ${{ secrets.GAMESERVER_HOST }}"
          ping -c 3 ${{ secrets.GAMESERVER_HOST }} || echo "Ping failed"

      - name: SSH key scan
        run: |
          ssh-keyscan -H ${{ secrets.GAMESERVER_HOST }} >> ~/.ssh/known_hosts
          echo "Added host to known_hosts"

      - name: Raw SSH connect debug
        run: |
          ssh -vvv -o ConnectTimeout=10 -o BatchMode=yes \
              ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} \
              'echo "SSH connection successful"; whoami; pwd; ls -la'

      - name: Test target directory
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} \
              'ls -la /srv/ && mkdir -p /srv/minecraft && ls -la /srv/minecraft'

      - name: Test sudo permissions
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} \
              'sudo -n systemctl --version || echo "No passwordless sudo for systemctl"'