# =====================================
# debug.yml – test SSH-verbinding
# =====================================
name: Debug SSH Connectivity
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      HOST: ${{ secrets.GAMESERVER_HOST }}
      USER: ${{ secrets.GAMESERVER_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Voeg host-key toe
        run: ssh-keyscan -t ed25519 -H "$HOST" >> ~/.ssh/known_hosts

      - name: Controleer login
        run: |
          ssh -o BatchMode=yes "$USER@$HOST" \
            'echo "Verbonden met $(hostname -f) als $(whoami)" && uptime'

      - name: Check tmux en Java (melding indien ontbreekt)
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          if ! command -v tmux >/dev/null; then
            echo "tmux niet gevonden. Installeer handmatig of voer ./start.sh op de server uit (eenmalig)."
          fi
          if ! java -version 2>&1 | grep -q "\(24\|17\)"; then
            echo "Java 17/24 niet gevonden. Installeer handmatig of voer ./start.sh op de server uit (eenmalig)."
          fi
          EOS