name: Deploy Minecraft Server

on:
  push:
    branches: [ Gameserver ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent (consistent met debug)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.GAMESERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o ConnectTimeout=10 ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'echo "SSH connection successful"'

      - name: Create target directory
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'mkdir -p /srv/minecraft'

      - name: Sync files via rsync
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='server-data' \
            --exclude='*.log' \
            ./ ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }}:/srv/minecraft/

      - name: Set permissions on target
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'chmod +x /srv/minecraft/start.sh'

      - name: Check if minecraft service exists
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'systemctl is-enabled minecraft || echo "Service does not exist"'

      - name: Restart Minecraft service
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'sudo systemctl restart minecraft'

      - name: Check service status
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} 'sudo systemctl status minecraft --no-pager'