# =====================================
# deploy.yml – Minecraft‑server uitrollen
# =====================================
name: Deploy Minecraft Server
on:
  push:
    branches: [ Gameserver ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      HOST: ${{ secrets.GAMESERVER_HOST }}
      USER: ${{ secrets.GAMESERVER_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH‑agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Voeg host‑key toe
        run: ssh-keyscan -t ed25519 -H "$HOST" >> ~/.ssh/known_hosts

      - name: Controleer tmux en Java
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          MISSING=0
          if ! command -v tmux >/dev/null; then
            echo "tmux ontbreekt. Installeer eerst handmatig (of run ./start.sh)."
            MISSING=1
          fi
          if ! java -version 2>&1 | grep -q "\(24\|17\)"; then
            echo "Java 17/24 ontbreekt. Installeer eerst handmatig (of run ./start.sh)."
            MISSING=1
          fi
          [ "$MISSING" -eq 0 ] || exit 1
          EOS

      - name: Bestanden kopiëren
        run: |
          if [ ! -d ./server-data ]; then
            echo "Map server-data/ ontbreekt in repo. Zet je serverbestanden daarin en commit opnieuw."
            exit 1
          fi
          rsync -avz --delete ./server-data/ "$USER@$HOST:/srv/minecraft/server-data/"

      - name: Herstart via tmux
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          tmux has-session -t mc 2>/dev/null && tmux kill-session -t mc || true
          tmux new-session -d -s mc 'cd /srv/minecraft && bash start.sh'
          echo "tmux‑sessie 'mc' opnieuw gestart"
          EOS
