# =====================================
# deploy.yml – Minecraft‑server uitrollen
# =====================================
name: Deploy Minecraft Server
on:
  push:
    branches: [ Gameserver ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      HOST: ${{ secrets.GAMESERVER_HOST }}
      USER: ${{ secrets.GAMESERVER_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Add host key
        run: ssh-keyscan -t ed25519 -H "$HOST" >> ~/.ssh/known_hosts

      - name: Zorg dat tmux en Java aanwezig zijn
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          install() { sudo -n true 2>/dev/null && sudo apt-get update -qq && sudo apt-get install -y "$@"; }
          command -v tmux >/dev/null || install tmux || echo "tmux niet geïnstalleerd (geen sudo)"
          java -version 2>&1 | grep -q "\(24\|17\)" || install openjdk-24-jdk || install openjdk-17-jdk || echo "Java niet geïnstalleerd (geen sudo)"
          EOS

      - name: Bestanden kopiëren
        run: rsync -avz --delete ./server/ "$USER@$HOST:/srv/minecraft/"

      - name: Server herstarten via tmux
        run: |
          ssh "$USER@$HOST" <<'EOS'
          set -e
          tmux has-session -t mc 2>/dev/null && tmux kill-session -t mc || true
          tmux new-session -d -s mc 'cd /srv/minecraft && bash start.sh'
          echo "tmux‑sessie 'mc' opnieuw gestart"
          EOS
