# ================================
# deploy.yml – minecraft deploy + service beheer
# ================================
name: Deploy Minecraft Server

on:
  push:
    branches: [ Gameserver ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAMESERVER_SSH_KEY }}

      - name: Add host key
        run: |
          ssh-keyscan -t ed25519 -H ${{ secrets.GAMESERVER_HOST }} >> ~/.ssh/known_hosts

      # 1) Zorg weer voor deps (tmux + Java) voor de deploy
      - name: Ensure deps present
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} '/bin/bash -s' <<'EOS'
          set -e
          if ! command -v tmux >/dev/null; then sudo apt-get update -qq && sudo apt-get install -y tmux; fi
          if ! java -version 2>&1 | grep -q "17\|24"; then sudo apt-get update -qq && sudo apt-get install -y openjdk-17-jdk; fi
          EOS

      # 2) Kopieer build‑files naar server
      - name: Sync server files
        run: |
          rsync -avz --delete ./server/ ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }}:/srv/minecraft/

      # 3) Start of herstart via tmux (valt terug op systemctl service als die bestaat)
      - name: Restart via tmux
        run: |
          ssh ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} <<'EOS'
          tmux has-session -t mc 2>/dev/null && tmux kill-session -t mc || true
          tmux new-session -d -s mc 'cd /srv/minecraft && bash start.sh'
          EOS

      # 4) systemd service
      - name: Reload systemd service (if exists)
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.GAMESERVER_USER }}@${{ secrets.GAMESERVER_HOST }} \
            'sudo systemctl is-enabled minecraft && sudo systemctl restart minecraft || echo "systemd service ontbreekt, tmux gestart"'
